### ISSUE TITLE
Using run.sh in parallel and category labels in the open-world setting

### ISSUE THREAD

**Issue by hkchengrex** [Ali2500/BURST-benchmark#4]
Hi, great work! The annotation and evaluation formats are clean and clear. Overall very easy to use. Loved it.

Two questions:
1. It seems like `run.sh` create temporary shell scripts for evaluation. I tried to run two in parallel (for two different trackers), but one reported a "cannot remove ‘_tmp_burst_eval.sh’: No such file or directory" which makes me wonder if the temporary scripts share the same path. If they do, I assume that I cannot trust their results since the latter overrides the previous one?  This "silent" failure seems dangerous.
2. In https://github.com/Ali2500/BURST-benchmark/blob/main/ANNOTATION_FORMAT.md, it tells me to replace `track_category_ids` with my predicted result. This confuses me a bit since I was working in the open-world setting. Currently I am setting all the category ids to `0`. Is this the correct thing to do?

**Comment by Ali2500** [comment]
Hi, thanks for the compliments. :)

1. The `run.sh` script is admittedly hacky. The reason I made it is because TrackEval requires a somewhat complicated directory structure which is great if you want to evaluate a bunch of results in one go, but is inconvenient if you just want to evaluate a single result file. I didn't think about the case where someone evaluates multiple results in parallel - this will indeed cause problems because of the temporary `_tmp_burst_eval.sh` file in `$TRACKEVAL_DIR`. Regarding result correctness: I think the results will be fine for all tasks except for open-world assuming that there is some delay between multiple calls to `run.sh`. The reason is that the predicted results are copied to a temporary directory and then loaded into memory soon afterwards, so overwriting the temporary predictions file after the read op should not effect the results. The open-world task however, internally calls the underlying TrackEval script three times (for each of the class splits), so there multiple simultaneous calls to `run.sh` will probably mess up the results.

I think the TLDR is that it's better to use TrackEval directly for such cases. You can take a look at the directory structure created by `eval/create_dirtree.py` and the command executed in `_tmp_burst_eval.sh`. The initial setup might be a bit finicky but after that it's just a matter of changing the path to the predictions file.

2. For the open-world and exemplar-guided tasks the `track_category_ids` field should be irrelevant. It's fine to have all zeros there (or even leave the ground-truth entries). I'll add this info to the readme.

**Comment by hkchengrex** [comment]
Great. Thanks!
